# Generated by Django 3.2.9 on 2021-11-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
