# Generated by Django 3.2.9 on 2021-11-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default='https://www.beavertontkd.com/wp-content/uploads/2017/04/default-image-620x600.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='ingredients'),
            preserve_default=False,
        ),
    ]
